#99 - Chatting을 Stomp Protocol로 구현한다.
mafia-together/backend pull request #118
Opened 2024-09-22 09:05 UTC by kpeel5839

### Description

Stomp Protocol, Redis, AOP를 활용하여 구현했습니다.

### 테스트 방법

1. 어플리케이션을 실행시킵니다. (Redis Host를 바꿔주세요.)
2. localhost:8080으로 입장합니다.
3. connect를 클릭하고, What is your name에 이름을 입력한 뒤, Send를 누르시면 됩니다.
4. 하지만, 3번을 해도 안될겁니다. 하하하 함-정 입니다.
5. 당연히, Code에 해당하는 Chat이 로컬 Redis에 존재하지 않으니 터지겠죠, `chatRepository.save(new Chat(code, new ArrayList<>()));` 를 ChatV2Service에 보이는바와 같이 추가해주세요.
<img width="880" alt="image" src="https://github.com/user-attachments/assets/fb44a750-a4ce-4ea3-8f36-131371aaad3c">
6. 어떻게 요청 보내는지와, Subscribe하는지를 자세하게 보고 싶다면, index.html, app.js를 봐주세요

2024-09-22 09:11 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/annotation/SendToChatWithRedis.java
> +}
JavaDoc까지 야무지게 남겨놓았습니다. 딱 보면 모를 것 같아서요.

2024-09-22 09:11 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/application/ChatV2Service.java
> +public class ChatV2Service {
v2를 아예 따로 팠어요.

2024-09-22 09:12 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/application/RedisMessageBroker.java
> +    public void onMessage(Message message, byte[] pattern) {
Redis에 Message를 Publishing하면 onMessage가 호출됩니다.

2024-09-22 09:13 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/aspect/SendToChatWithRedisService.java
> +public class SendToChatWithRedisService {
@SendToChatWithRedis 어노테이션이 붙어 있는 메서드를 찾아, 해당 메서드가 반환하는 Message를 StringRedisTemplate으로 쏴주는 Service입니다.

2024-09-22 09:13 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/aspect/SendToChatWithRedisService.java
> +    private static String replacePlaceholders(String template, Map<String, String> parameterToValue) {
텍스트 대치도 가능하도록 하였습니다.

ex) /sub/chat/{code} --> /sub/chat/hello

2024-09-22 09:13 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/ui/ChatV2Controller.java
> +    }
결과물입니다.

2024-09-22 09:14 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/config/StompChannelInterceptor.java
> +public class StompChannelInterceptor implements ChannelInterceptor {
Auth를 클라이언트가 해독하는 것은 말이 안된다고 생각했습니다. 그렇기에 Interceptor를 추가하여 해독해서 넘겨줍니다.

2024-09-22 09:14 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/config/WebsocketConfig.java
> +    }
interceptor 등록

2024-09-22 09:15 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/config/WebsocketConfig.java
> +    }
RedisMessageListener를 등록해주고, container에 trigger(Topic으로 판단)까지 설정해줍니다.

2024-09-22 11:17 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/MafiaTogetherApplicationTests.java
> -}
이거 필요한건가요?! Import(RedisTestConfig.class) 추가하면 Test들 안터지기는 하는데, 이게 왜 필요한지 정확히 몰라서요. 설명 한번마안

2024-09-24 16:42 UTC, waterricecake requested changes
와 너무 어렵네요;;;
STOMP 과정자체가 어려워서 리뷰하는데 조금 오래걸렸던것 같습니다.
진짜 보면서 와 고민 많이 하셨겠구나 생각이 들었어요.
근데 진짜 재밌네요;; 와 interceptor에서 요청의 분기점들을 이해하는데 힘들..... (아 이건 맽의 코드가 어렵다는게 아니라 스프링의 Web Socket 구현을 찾아서 보는데 어려웠다는 뜻입니다)
리뷰하면서도 되게 많은걸 배웠네요!

2024-09-24 16:42 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/chat/ui/ChatV2Controller.java
> +    }
이게 채팅 페이지 처음 랜더링할때 이전 채팅기록때문에 만든거죠?

2024-09-24 16:42 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/chat/aspect/SendToChatWithRedisService.java
> +        String topic = replacePlaceholders(sendToChatWithRedisAnnotation.value(), parameterToValue);
구독 토픽이 `code` 가 아니라 `/sub/chat/{code}` 가 되는 건가요?

2024-09-24 16:42 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/chat/application/ChatV2Service.java
> +public class ChatV2Service {
레거시를 위한 v2....

2024-09-24 16:42 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/chat/application/dto/request/ChatRequest.java
> +        String content
아 contents는 물리적으로 셀수있는 내요물을 뜻할때 쓰이고 content는 셀수 없거나 창작물을 의미할때 쓰는군요.. 전 다 contents인줄 ㅋㅋㅋ
근데 이거 바꿀꺼면 API 문서랑 front도 수정해야함다 (해줘)

2024-09-24 16:42 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/common/AuthExtractor.java
> +package mafia.mafiatogether.common;
common과 config 같이 전범위에서 쓰이는 클래스를 모은 상위 패키지를 만드는건 어떤가요?(`global`같은거)

2024-09-24 16:42 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/chat/aspect/SendToChatWithRedisService.java
> +        mafia.mafiatogether.chat.annotation.SendToChatWithRedis sendToChatWithRedisAnnotation = method.getAnnotation(mafia.mafiatogether.chat.annotation.SendToChatWithRedis.class);
이 부분을 `import mafia.mafiatogether.chat.annotation.SendToChatWithRedis` 하지않은 이유가 있을까요?

2024-09-24 16:42 UTC, waterricecake commented on src/main/resources/static/app.js
> +const stompClient = new StompJs.Client({
역시 풀스택....

2024-09-24 16:42 UTC, waterricecake commented on src/main/resources/static/app.js
> +    stompClient.subscribe('/sub/chat/aGVsbG86cG93ZXJhc3M=', (greeting) => {
여기 있는 방 코드는 임의로 넣으신건가요?

2024-09-24 16:42 UTC, waterricecake commented on src/test/java/mafia/mafiatogether/MafiaTogetherApplicationTests.java
> +@Import(RedisTestConfig.class)
👍

2024-09-24 16:42 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/common/AuthExtractor.java
> +    public static String[] extractByAuthorization(String authorization) {
나중에 암호화 로직을 바꾼다면 여기만 건들면 되겠군요

2024-09-24 16:44 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/chat/ui/ChatV2Controller.java
> +    }
여기 어노테이션 이해하는게 제일 어려웠음요 ㅋㅋㅋㅋㅋㅋㅋㅋ Websocket 겁나 복잡 근데 AOP는 진짜 짱짱맨

2024-09-24 22:05 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/aspect/SendToChatWithRedisService.java
> +        mafia.mafiatogether.chat.annotation.SendToChatWithRedis sendToChatWithRedisAnnotation = method.getAnnotation(mafia.mafiatogether.chat.annotation.SendToChatWithRedis.class);
엇!! 나 이거 바꾼줄일았는데 여기 숨어있었네 고마워요

2024-09-24 22:13 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/aspect/SendToChatWithRedisService.java
> +        String topic = replacePlaceholders(sendToChatWithRedisAnnotation.value(), parameterToValue);
맞아용

2024-09-24 22:14 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/ui/ChatV2Controller.java
> +    }
맞아요! 계속 호출하는 것이 아니라 말씀하신 것처럼 다음 날로 넘어갔을때나 혹은 팅겼다가 재 접속 했을때 해당 메서드 호출할 것 같아요

2024-09-24 22:14 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/application/dto/request/ChatRequest.java
> +        String content
누가 기획자지?

2024-09-24 22:15 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/common/AuthExtractor.java
> +package mafia.mafiatogether.common;
Common을 global과 같은 의미로 만든 것이긴해요. Global이라는 패키지 명이 더 나을까요??

2024-09-24 22:15 UTC, kpeel5839 commented on src/main/resources/static/app.js
> +const stompClient = new StompJs.Client({
복붙인딩~~

2024-09-24 22:17 UTC, kpeel5839 commented on src/main/resources/static/app.js
> +    stompClient.subscribe('/sub/chat/aGVsbG86cG93ZXJhc3M=', (greeting) => {
Hello:powerass를 암호화한 것입니다. 임의로 넣은거에요 ㅋㅋㅋㅋㅋㅋ hello라는 코드를 가진 방에 powerass가 입장한 것을 가정하고요

2024-09-24 22:18 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/common/AuthExtractor.java
> +    public static String[] extractByAuthorization(String authorization) {
맞아용 굳굳!! Util로 뺀게 마음에 들지는 않지만 킹쩔 수 없쬬

2024-09-25 05:00 UTC, thdwoqor approved these changes
굿

2024-09-25 05:00 UTC, thdwoqor commented on src/main/resources/static/app.js
> +    stompClient.subscribe('/sub/chat/aGVsbG86cG93ZXJhc3M=', (greeting) => {
powerass?

2024-09-25 05:00 UTC, thdwoqor commented on src/main/java/mafia/mafiatogether/common/AuthExtractor.java
> +package mafia.mafiatogether.common;
둘다 좋아요

2024-09-25 05:00 UTC, thdwoqor commented on src/main/java/mafia/mafiatogether/chat/aspect/SendToChatWithRedisService.java
> +        String topic = replacePlaceholders(sendToChatWithRedisAnnotation.value(), parameterToValue);
@DestinationVariable("code") 추출하기 어려워서 그냥 path로 한건가?

2024-09-25 05:00 UTC, thdwoqor commented on src/main/java/mafia/mafiatogether/config/RedisMessageBroker.java
> +        simpMessagingTemplate.convertAndSend(new String(message.getChannel()), message.getBody());
얘가 `@SendTo` 역할을 하는구나

2024-09-25 05:00 UTC, thdwoqor commented on src/main/java/mafia/mafiatogether/config/StompChannelInterceptor.java
> +public class StompChannelInterceptor implements ChannelInterceptor {
클라이언트단에서 /pub/chat/aGVsbG86cG93ZXJhc3M=
이런식으로 요청을 보낸걸
/pub/chat/hello/powerass 이렇게 변환하는군

2024-09-25 07:58 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/common/AuthExtractor.java
> +package mafia.mafiatogether.common;
패키지명을 바꾸기 보단 한 패키지안에서 분리하더라도 전범위에 쓰이는건 모으면 좋을것 같다는 의미였습니다. 지금 config랑 common이랑 따로 있길래...

2024-09-25 08:11 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/config/RedisMessageBroker.java
> +        simpMessagingTemplate.convertAndSend(new String(message.getChannel()), message.getBody());
맞지

2024-09-26 09:37 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/config/StompChannelInterceptor.java
> +public class StompChannelInterceptor implements ChannelInterceptor {
맞아용

2024-09-26 09:38 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/config/StompChannelInterceptor.java
> +public class StompChannelInterceptor implements ChannelInterceptor {
hello/ 뒤에 붙은 단어도 굉장히 중요하지 여기서

2024-09-26 09:39 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/chat/aspect/SendToChatWithRedisService.java
> +        String topic = replacePlaceholders(sendToChatWithRedisAnnotation.value(), parameterToValue);
Path???
아아아 code 뿐만 아니라 나중에 구독하는 사람한테 뿌리는 방법이 되게 다양할 수 있잖아.

그래서 기존의 어노테이션과 비슷하게 pathvariable로 한거야 이게 가장 확장성이 좋아보여서

2024-09-26 09:40 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/common/AuthExtractor.java
> +package mafia.mafiatogether.common;
config랑 common은 좀 뭔가 다른 느낌으로 느껴지긴하는데, 제 생각보다 더 좋은 의견인 것 같긴하네요. 그렇게 바꾸겠습니당~

2024-09-26 09:45 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/common/AuthExtractor.java
> +package mafia.mafiatogether.common;
https://github.com/mafia-together/backend/pull/118/commits/351217f404825fc87ce7800b48b933756b4de1e2

2024-09-26 09:46 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/common/AuthExtractor.java
> +package mafia.mafiatogether.common;
https://github.com/mafia-together/backend/pull/118/commits/b9c3a6a7752dc479fcaa9c67de05966362d55b01

2024-09-29 08:03 UTC, waterricecake approved these changes
고생했어요~

2024-09-29 08:11 UTC, merged