#142 - 대기방에서 SSE를 통해 인원을 받아온다.
mafia-together/backend pull request #143
Opened 2024-10-27 12:16 UTC by kpeel5839

사용자가 방에 입장했을 때 (join), SSE를 통해 인원을 client에게 쏴줍니다.

- 테스트도 야무지게 짰습니다.

2024-10-28 05:12 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/lobby/application/LobbyEventListener.java
> +    private final SseEmitterRepository sseEmitterRepository;
이러면 Lobby가 Game에 의존성이 생기지 않나요??
문득 생각이 든건데 SSE 보내는것도 Service단에서 할게 아니기 때문에 Websocket처럼 서비스단에서 로직을 분리해서 common으로 이동해야하지않나라는 생각도 들긴했어요.
왜냐면 SSE도 통신 프로토콜인데 service 계층이 아닌 그 앞단에서 처리해야할 것 같다고 생각이 드네요.
그래서 제가 제안해 보는 것은 SseRepo를 Common으로 옮기고 해당 로직들을 Aspect(나 AOP 중독인듯)로 분리해보는건 어떨까요? (그냥 의견 제시입니다)

2024-10-28 05:30 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/lobby/application/LobbyEventListener.java
> +    private final SseEmitterRepository sseEmitterRepository;
LobbyEventListener를 따로 둔 것도, Response에도 따로 선언했던 것이, Game과의 의존성을 끊어내기 위함이었는데 SseEmitterRepository가 Game안에 들어있을 거라고는 생각도 못했네요 ;; 

이거는 SseEmitter만 옮기면 되는 문제 같은데요.

맞아요, 그리고 SSE 보내는 것 자체를 Service에서 하는 것에 대한 살짝 의구심이 들긴했는데 기존 방식 그대로 따라갔거든요. 근데, 그렇다고 또 AOP로 분리하기는 뭔가 AOP 중독 같기도 ;;

2024-10-28 05:31 UTC, waterricecake requested changes
고생하셨습니다~ 맽
몇가지 코맨트 달았습니다!

2024-10-28 05:31 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepository.java
> +            throw new IllegalArgumentException("sse emitter of user not found");
Illegal 말고 ServerException이나 AuthException으로 에러를 던지는게 어떨까요?

2024-10-28 05:31 UTC, waterricecake commented on src/test/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepositoryTest.java
> +        inMemorySseEmitterRepository.save("code", "name2", findOutSseEmitter);
모킹의 신...
확실히 모킹을 하니까 단위별로 테스트하기 편하네요.
다음에 테스트 리펙토링할때 다 적용해봐야겠네요

2024-10-28 05:31 UTC, waterricecake commented on src/test/java/mafia/mafiatogether/lobby/application/dto/response/LobbyInfoResponseTest.java
> +class LobbyInfoResponseTest {
```suggestion
@SuppressWarnings("NonAsciiCharacters")
class LobbyInfoResponseTest {
```
dto 테스트를 하시게된 이유가 뭔가요?

2024-10-28 05:31 UTC, waterricecake commented on src/test/java/mafia/mafiatogether/lobby/application/LobbyEventListenerTest.java
> +class LobbyEventListenerTest {
```suggestion
@SuppressWarnings("NonAsciiCharacters")
@ExtendWith(MockitoExtension.class)
class LobbyEventListenerTest {
```

2024-10-28 05:31 UTC, waterricecake commented on src/test/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepositoryTest.java
> +class InMemorySseEmitterRepositoryTest {
```suggestion
@SuppressWarnings("NonAsciiCharacters")
class InMemorySseEmitterRepositoryTest {
```

2024-10-28 05:32 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepositoryTest.java
> +class InMemorySseEmitterRepositoryTest {
호우쮀엣

2024-10-28 05:32 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/lobby/application/LobbyEventListenerTest.java
> +class LobbyEventListenerTest {
호우쮀엣

2024-10-28 05:33 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/lobby/application/dto/response/LobbyInfoResponseTest.java
> +class LobbyInfoResponseTest {
lobby, name을 받아서 조금의 stream 연산을 행하기 때문에 했던 것 같아요. 사실 있어도 그만 안해도 그만인데, 테스트는 다다익선이라고 생각해서요

2024-10-28 05:33 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepositoryTest.java
> +        inMemorySseEmitterRepository.save("code", "name2", findOutSseEmitter);
근데 너무 길죠 ?

2024-10-28 05:33 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepository.java
> +            throw new IllegalArgumentException("sse emitter of user not found");
오우쮓, 심지어 영어 메시지에요

2024-10-28 05:35 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/lobby/application/LobbyEventListener.java
> +    private final SseEmitterRepository sseEmitterRepository;
제가 넣은거긴 SSE를 Service에 넣긴 했지만... 옮기고 싶군요. 아니면 이번 PR에서는 LobbyEvent만 GameEvent로 로직을 옮기고 SSE를 Game과 분리하는건 다음 리펙토링때 작업하는 건 어떤가요? 작업 단위가 커질수도 있을것 같아서

2024-10-28 05:35 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepository.java
> +            throw new IllegalArgumentException("sse emitter of user not found");
ServerException이 조금 더 나아보이네요 뭔가 AuthException이라기에는 조금 애매한 구석이 있는 것 같죠?

2024-10-28 05:36 UTC, waterricecake commented on src/test/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepositoryTest.java
> +        inMemorySseEmitterRepository.save("code", "name2", findOutSseEmitter);
근데 단위별로 짧게 나눠져서 보기 편할지도? 지금은 거의 controller 통합테스트에서 여러개 테스트하고 있자나요. 단위별로 나누면 더 보기 쉬울수 있을꺼 같아요

2024-10-28 05:37 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/lobby/application/LobbyEventListener.java
> +    private final SseEmitterRepository sseEmitterRepository;
그것도 괜찮은데, 맘에 들지는 않네요. Lobby의 일을 Game으로 넘겨서 처리한다.. 의미상으로 마음에 들지 않아요.

하지만, 달리 말대로 너무 작업단위가 커질 수 있으니, 추후 다시 분리하도록 하는게 좋을 것 같아요

2024-10-28 05:37 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepositoryTest.java
> +        inMemorySseEmitterRepository.save("code", "name2", findOutSseEmitter);
좋습니다. 테스트 조금씩 보충시켜나가보죠

2024-10-29 05:16 UTC, waterricecake approved these changes
고생하셨습니다 맽!!!!

2024-10-30 13:16 UTC, thdwoqor approved these changes
고생했어

2024-10-30 13:16 UTC, thdwoqor commented on src/main/java/mafia/mafiatogether/lobby/application/dto/response/LobbyInfoResponse.java
> +                lobby.getMaster().getName().equals(myName),
```java
lobby.getMaster().getName().equals(myName)
```
이런거 isMaster 메서드 만들어서 lobby에 로직 넣는건 어때

2024-10-30 13:16 UTC, thdwoqor commented on src/test/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepositoryTest.java
> +        ThrowingCallable actual = () -> inMemorySseEmitterRepository.findByCodeAndName("code", "name");
오우 이런거 처음봐

2024-10-30 13:32 UTC, thdwoqor commented on src/main/java/mafia/mafiatogether/lobby/application/LobbyEventListener.java
> +    private final SseEmitterRepository sseEmitterRepository;
@kpeel5839 
궁금한게 LobbyEventListener는 왜 lobby가아니라 game에 있는거야?

2024-10-30 17:21 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/lobby/application/LobbyEventListener.java
> +    private final SseEmitterRepository sseEmitterRepository;
> 제가 넣은거긴 SSE를 Service에 넣긴 했지만... 옮기고 싶군요. 아니면 이번 PR에서는 LobbyEvent만 GameEvent로 로직을 옮기고 SSE를 Game과 분리하는건 다음 리펙토링때 작업하는 건 어떤가요? 작업 단위가 커질수도 있을것 같아서

이것때문에 그렇게 했어 일단, game 에서 다 참조하고 있는 의존관계를 가지고 있으니까

2024-10-30 17:22 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/game/domain/InMemorySseEmitterRepositoryTest.java
> +        ThrowingCallable actual = () -> inMemorySseEmitterRepository.findByCodeAndName("code", "name");
오유쉿

2024-10-30 17:22 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/lobby/application/dto/response/LobbyInfoResponse.java
> +                lobby.getMaster().getName().equals(myName),
그것도 좋지이

2024-10-31 12:26 UTC, merged