feat 채팅 조회/전송 기능 구현
mafia-together/backend pull request #8
Opened 2024-04-17 15:38 UTC by waterricecake

#7 채팅 기능 구현

- Chat : 전체 잡담 내용 (List로 Message를 가지고 있음)
- Message : 메세지 하나

추가
- Room의 players를 List<Player> -> Map<String, Player>로 변경
    - chat저장시 player를 찾아야하는데 List일 경우 stream().filter()로 찾아야함 -> 이것보다 Map일 경우 코드도 간결해지고 (어차피 인원 수가 많지는 않을거라 상관없겠지만) 시간복잡도도 낮아짐
    - 추후 이름으로 Player를 찾아야할 경우가 많아질거라 예상 (ex) 투표 지목 대상의 상태(alive) 변경)
    - 꼭 이걸로 하자는 의견은 아님 (저번에도 상황오면 보고 하자고 했던거 같아서 근데 이번에 Player를 찾아야할 경우가 생겨서 일단 넣어봄)

2024-04-18 16:40 UTC, thdwoqor approved these changes
👍

2024-04-18 16:40 UTC, thdwoqor commented on src/main/java/mafia/mafiatogether/domain/Chat.java
> +@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
어노테이션 피라미드 식으로 배치하는건 어떨까?
반 피라미드식 or 피라미드식 하나 정하면 좋을듯?

2024-04-18 16:40 UTC, thdwoqor commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +    public ResponseEntity<Void> sendChat(
서버 입장에서 채팅을 저장하는 saveChat이 어떰?

2024-04-18 16:40 UTC, thdwoqor commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +                new HashMap<>(),
ConcurrentHashMap
동시성 문제는 따로 없겠지?

2024-04-19 07:50 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/domain/Chat.java
> +@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
피라미드 ㄱ

2024-04-19 07:51 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +    public ResponseEntity<Void> sendChat(
그럼 이것도 repository라고 생각하고 네이밍할께

2024-04-19 07:52 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +                new HashMap<>(),
있을수도? 참가 동시에 여러명하면서 생기거나 하지 않을까?

2024-04-19 10:02 UTC, kpeel5839 reviewed
HashMap으로 바꾸는 것 되게 좋은 의견인 것 같아요!
역시 달리햄은 달라 논술왕!

간단한 의견들 몇개 남겼어요!
당연하게 전부 반영할 필요없고, 애매한 부분이나 아니라고 생각되는 부분들에 대해서 다시 코멘트 달아주시면 감사할 것 같아요.
고생하셨습니다!

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/service/ChatService.java
> +                                message.isOwner(name)
저는 이런식의 정팩메도 조금 좋아하는 것 같아요. 어떻게 생각하세요??? Response 가 domain 을 알고 있는 것은 크게 문제가 된다고 생각하지 않아서요!
```java
public List<ChatResponse> getChat(final String code, final String name) {
    final Room room = roomManager.findByCode(code);
    final Chat chat = room.getChat();
    return chat.getMessages().stream()
        .map(message -> ChatResponse.ofByName(message, name))
        .toList();
}

// ChatResponse
public static ChatResponse ofByName(Message message, String name) {
    return new ChatResponse(
        message.getName(),
        message.getContents(),
        message.getTimestamp(),
        message.isOwner(name)
    );
}
```

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/service/dto/ChatResponse.java
> +}
해당 객체는 record로 가져가는 것이 조금 더 편할 수도 있을 것 같아요! getter도 단순하고, 위와 같은 어노테이션도 추가적으로 안붙여도 되니까요.
재백짱이랑 동연짱은 어떻게 생각하세요?

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/domain/Message.java
> +    public static Message of(final Player player, final String contents){
final 을 전부 붙이는 것이 Convention인가 보군요. 인지하겠습니당

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/domain/Chat.java
> +@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
저도 피라미드식이 좋은 것 같아요

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +    public ResponseEntity<Void> sendChat(
저도 항상 Controller, Service 네이밍에 고민이 많았는데, 이렇게 하면 명쾌하겠네요

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +        return ResponseEntity.ok(chatService.getChat(playerInfoDto.code(), playerInfoDto.name()));
code 가 뭐에요?

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
오 redirection url 안 넘길려고 이렇게 한건가요 👍

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +                new HashMap<>(),
동시성 신경써서 나쁠 이유는 없을 것 같아요, 많지는 않지만, 다수의 사용자들이 들어올 수 있는 환경이기에 달리 말처럼 동시성 문제가 발생할 수도 있을 것 같고요

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +        }
나중에 예외에 대한 일괄처리를 할 때 표준예외가 아닌 CustomException으로 감싸는 것도 좋을 것 같아요! 현재는 빠르게 서비스를 출시해야하니까 이렇게 고고!

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/service/ChatService.java
> +        chat.save(Message.of(player,chatRequest.contents()));
나 컨벤션 너무 불편해 ㅡㅡ

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/service/dto/ChatRequest.java
> +}
오잉 이거는 record네? response는 record로 하지 않은 이유가 있나요?

2024-04-19 10:02 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/controller/ChatControllerTest.java
> +        player = new Player("power");
matthew도 넣어주세요

2024-04-19 10:02 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +        }
그리고 findPlayer의 예외상황이라던가, joinPlayer 메서드의 테스트는 추가되지 않은것으로 보여요. 물론 joinPlayer는 hashMap에다가 집어넣기만 하는 동작을 수행하고 있어서, 크게 테스트 할 필요가 없어보이기는 하지만, findPlayer는 예외동작을 확인하기 위해서라도 테스트가 필요해보여요! 달리는 어떻게 생각하시나요?

빠른 출시를 위해서 통합테스트만 작성하고 있는 것이라면 OK이지만, 나중에 어짜피 세세한 테스트들을 추가해야 한다는 것이 개인적인 생각이라서, 이 부분에서 추후 비용이 많이 들어갈까봐 걱정되어 말씀드립니다!

2024-04-19 10:02 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/controller/RoomControllerTest.java
> +        Assertions.assertThat(room.getPlayers()).containsKey("power");
나도 해줘잉

2024-04-19 10:03 UTC, kpeel5839 requested changes
모르고 comment 로 남겼네 ;;

2024-04-19 10:18 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +                new HashMap<>(),
그러면 ConcurrentHashMap으로 구현해둘께요!

2024-04-19 10:46 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +        }
빠르게 구현하다가 놓친 부분이긴한데... 저도 예외 상황들을 추후에 이슈파서 넣어야겠다고 생각하고 있었습니다. 나중에 CustomException 만들때 같이 테스트도 구현해야지 라고 생각하고 있었습니다. 맽은 어떻게 생각하시나요? 지금 넣는다? 아니면 CustomException 구현하면서 테스트를 짠다?

2024-04-19 10:46 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/service/ChatService.java
> +                                message.isOwner(name)
오 나 왜이랬지? 저 정팩매로 바꿀려고 message.isOwner()만든건데;;;;;;바로 반영하겠습니다ㅎㅎ 저도 정팩매를 더 선호합니다.

2024-04-19 10:46 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/service/dto/ChatRequest.java
> +}
제가 record를 사용안하다 보니 깜빡한거 같습니다!! 바로 반영

2024-04-19 10:46 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/service/dto/ChatResponse.java
> +}
rehundred랑 저번에 레코드 사용하기로 하기로 했었요! 반영하겠습니다! 제가 실수했군요;;

2024-04-19 10:46 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
ResponseEntity.create()는 뭘 무조건 넣어주어야 하더라고요

2024-04-19 10:46 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +        return ResponseEntity.ok(chatService.getChat(playerInfoDto.code(), playerInfoDto.name()));
그 방을 식별하는 코드입니다. 어 그니까 방 제목이요!

2024-04-19 10:46 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/service/ChatService.java
> +        chat.save(Message.of(player,chatRequest.contents()));
`option + command + l` 생활화....

2024-04-19 15:43 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/service/dto/ChatResponse.java
> +}
ㅋㅋㅋㅋ rehundred ㅋㅋㅋ

2024-04-19 15:44 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +        return ResponseEntity.ok(chatService.getChat(playerInfoDto.code(), playerInfoDto.name()));
이해했어요. 제가 코드를 이해하려고 하지 않았나보군요

2024-04-19 15:44 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +        return ResponseEntity.status(HttpStatus.CREATED).build();
마자아여여

2024-04-19 15:45 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +        }
음 CustomException 을 구현할 때 같이 테스트를 짜는 방법도 좋은 방법인 것 같아요. 하지만, 추후에 Exception 검증 부분의 코드만 수정하면 되니까 많은 비용이 드는 작업은 아닐 것 같아요.
그것보다, 현재 테스트 케이스를 완벽하게 해서 작업속도를 향상시킬 수 있도록 하고, 추후에 CustomException 으로 수정할 때, 그 때 그냥 조금 코드만 수정하는 방향은 어떠신가요?

2024-04-19 15:45 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/service/ChatService.java
> +        chat.save(Message.of(player,chatRequest.contents()));
생활화하세용!

2024-04-19 15:46 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/service/dto/ChatRequest.java
> +}
네넵!👍

2024-04-19 17:52 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +        }
하긴 그렇게 오래걸리는 작업도 아닌데 미리 해두는게 좋겠네요. 솔직히 빠르게하다가 놓치고 안하고 있었는데 어차피 할거면 이번 PR에 해두는게 좋겠어요.
[aac1457](https://github.com/mafia-together/backend/pull/8/commits/aac1457938103af547ae7d0098d72fd1aadf0f39)

2024-04-19 17:52 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/domain/Chat.java
> +@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
[ae4f8e7](https://github.com/mafia-together/backend/pull/8/commits/ae4f8e7a36c21a1bd2943ea07372cd658ca1dd72)
반영

2024-04-19 17:52 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +    public ResponseEntity<Void> sendChat(
근데 이부분 RoomController보면 생성 api는 create으로 되어있던데 여기도 통일해두는게 좋을꺼 같다고 생각함
Controller, Service의 메서드 명은 create{대상명}
repository는 save{대상명}으로 하는건 어떻습니까?
[0245430](https://github.com/mafia-together/backend/pull/8/commits/0245430f81c2987720d740e5f639f9a40177c670)

2024-04-19 17:52 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/domain/Room.java
> +                new HashMap<>(),
[0cf116b](https://github.com/mafia-together/backend/pull/8/commits/0cf116b4e58ef94da646f07b8a80eaaabc28514c)

2024-04-20 04:14 UTC, kpeel5839 approved these changes
달리 고생하셨어요! 그냥 코멘트 확인만 부탁드려용

2024-04-20 04:14 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/service/ChatService.java
> +                .map(message -> ChatResponse.byOfName(message, name))
byOfName이라고 네이밍을 많이 하나요? 제가 영어를 잘 못해서 이게 자연스러운지 모르겠어서요!

아니면 그냥 by를 빼고 ofName은 어떠세요? 그렇다기에는 message도 들어가서 조금 부자연스러운가?

2024-04-20 04:14 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/domain/Chat.java
> +    public void save(final Message message) {
진짜 미쳐부러~ option+command+l 습관화 가즈아

2024-04-20 04:14 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +    public ResponseEntity<Void> createChat(
이거 Repository 식으로 가려면 saveChat이라고 해야하지 않을까요? 파워 의견도 그랬고요. create이라고 네이밍을 변경한 이유가 있을까용~?

2024-04-20 04:14 UTC, kpeel5839 commented on src/test/java/mafia/mafiatogether/controller/ChatControllerTest.java
> +        );
좋아요!!! 역시 달리입니다. 근데 제가 이야기 한 부분은 Service 테스트이긴 했는데 그래도 충분한 것 같아요 고생하셨어요!

2024-04-20 05:20 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +    public ResponseEntity<Void> createChat(
아 그 RoomController에서 roomcreate를 되어있어서 통일시킬려고 했는데 제가 잘이해를 못했엇나봐요;; repository식이라는 게 domain에 있는 room이나 chat이 결국 repository랑 같은 역할이어서 네이밍을 이런식으로 한거였고 roomController의 네임이 create여서 controller에서는 create를 사용하는건가 라고 생각한건데 그냥 save로 통일하는편이 머리 안아플꺼같네요ㅎㅎ

2024-04-20 05:22 UTC, waterricecake commented on src/main/java/mafia/mafiatogether/service/ChatService.java
> +                .map(message -> ChatResponse.byOfName(message, name))
걍 머리 안아프게 여러개 들어간거는 of, 한개는 from으로 하죠. 어차피뭐가 들어가는 지는 뒤에 인자 들어가면서 of(message, name)이런 식이니까 잘 읽힐꺼 같아요

2024-04-20 05:34 UTC, merged

2024-04-20 05:35 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/service/ChatService.java
> +                .map(message -> ChatResponse.byOfName(message, name))
맞아요 ㅋㅋㅋㅋ 근데 이제 여러 종류의 정팩메가 생기는 경우를 고려한 거 였긴 하는데, 사실 그럴 일도 크게 없으니까, 그냥 넘어가도록 하죠!!

2024-04-20 05:40 UTC, kpeel5839 commented on src/main/java/mafia/mafiatogether/controller/ChatController.java
> +    public ResponseEntity<Void> sendChat(
제가 이 댓글을 못봤네요;;